[package]
name = "yt-sync"
version = "2.3.5"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive", "unicode"] }
dirs = "5.0.1"
indicatif = "0.17.8"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
toml = "0.8.19"
