# Set the default for dependencies.
[profile.dev.package."*"]
opt-level = 3

# Turn on a small amount of optimisation in development mode.
[profile.dev]
opt-level = 1

[target.'cfg(any(windows, unix))']
rustflags = ["-Ctarget-cpu=native"]

[profile.release]
lto = true
codegen-units = 1
debug = true
opt-level = 3
